[package]
name = "bundle-schema"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.4", features = ["derive", "unicode"] }
log = "0.4.21"
serde_json = "1.0.115"
simple_logger = { version = "4.3.3", features = ["stderr"] }
url = "2.5.0"
